In [2]:
import numpy as np

In [19]:
x = np.matrix([[1,2,3],
             [4,5,6],
             [7,8,9]])

idx = np.matrix([[0],[1],[2]])


In [24]:
print(x[np.arange(3),idx.T].reshape(3,1))

[[1]
 [5]
 [9]]


In [26]:
print (x - idx)

[[1 2 3]
 [3 4 5]
 [5 6 7]]
